package com.redsquare.citizen.systems.psychology;

public enum PersonTraits {
  PARENTAL_INSTINCTS, AMBITION, IDEALISM,
  CHARISMA, SELF_ESTEEM, INTELLECT, EMPATHY,
  AGREEABLENESS, RUTHLESSNESS, RISK_TAKING, LOYALTY,
  ATTRACTIVENESS, OPEN_MINDEDNESS
}
